//Stories
export const GET_STORIES = "GET_STORIES";
export const ADD_STORY = "ADD_STORY";
export const DELETE_STORY = "DELETE_STORY";
export const STORIES_LOADING = "STORIES_LOADING";

//Story Sections
export const GET_STORY_SECTIONS = "GET_STORY_SECTIONS";
export const ADD_STORY_SECTION = "ADD_STORY_SECTION";
export const DELETE_STORY_SECTION = "DELETE_STORY_SECTION";
export const STORY_SECTIONS_LOADING = "STORY_SECTIONS_LOADING";

// Authentication
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT FAILURE";
export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

//Authors
export const GET_AUTHORS = "GET_AUTHORS";
export const ADD_AUTHOR = "ADD_AUTHOR";
export const DELETE_AUTHOR = "DELETE_AUTHOR";
export const AUTHORS_LOADING = "AUTHORS_LOADING";

// User Profile
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";
